# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{freeberry_auth}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Igor Galeta", "Pavlo Galeta"]
  s.date = %q{2010-11-25}
  s.description = %q{Social authorization system via Loginza or RPX}
  s.email = %q{galeta.igor@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "app/controllers/freeberry_auth/accounts_controller.rb",
     "config/routes.rb",
     "lib/freeberry_auth.rb",
     "lib/freeberry_auth/account.rb",
     "lib/freeberry_auth/authorized_system.rb",
     "lib/freeberry_auth/engine.rb",
     "lib/freeberry_auth/version.rb",
     "lib/generators/freeberry_auth/USAGE",
     "lib/generators/freeberry_auth/install_generator.rb",
     "lib/generators/freeberry_auth/templates/create_accounts.rb"
  ]
  s.homepage = %q{https://github.com/galetahub/freeberry_auth}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{freeberry_auth}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Social authorization system}
  s.test_files = [
    "test/freeberry_auth_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

